version: v2beta1
name: pipelines2

pipelines:
  helper:
    steps:
      - run: |-
          echo "Hello World!"
  dev:
    steps:
      - run: |-
          run_pipelines helper
         
          #build_images test --set image=${IMAGE}
          
          #create_deployments test2
          
          # Start development mode for test here
          #start_dev test --set imageSelector=${runtime.images.test} \
          #               --set terminal.command=sh