version: v2beta1
name: pipelines

pipelines:
  test:
    steps:
      - run: |-
          start_dev test --set imageSelector=ubuntu \
                         --set logs.disabled=false

  dev:
    steps:
      - run: |-
          create_deployments test --set helm.componentChart=true \
                                  --set helm.values.containers[0].image=ubuntu \
                                  --set helm.values.containers[0].command='{sh,-c,echo "Hello World" && sleep 99999999}'
          
          run_pipelines test
          echo "After"