version: v2beta1
name: pipelines

vars:
  - name: IMAGE
    value: loftsh/javascript:latest

deployments:
  - name: quickstart
    helm:
      componentChart: true
      values:
        containers:
          - image: ${IMAGE}
            command: ["sleep", "10000000000"]

dev:
  quickstart:
    imageSelector: ${IMAGE}
    forward:
      - port: 3000
    sync:
      - printLogs: true

pipelines:
  dev:
    steps:
      - run: |-
          deploy --all
          start_dev --all
