version: v2beta1
name: pipelines

pipelines:
  test3:
    steps:
      - run: |-
          echo "Hello World 3"
  test2:
    steps:
      - run: |-
          echo "Hello World 2"
  test:
    steps:
      - run: |-
          echo "Hello World 1"
  dev:
    steps:
      - run: |-
          run_pipelines test test2 test3 --sequential
          echo "After"