version: v2beta1
name: pipelines

vars:
  - name: IMAGE2
    value: testme2

imports:
  - path: test.yaml

pipelines:
  dev:
    steps:
      - run: |-
          echo ${IMAGE}
          
          echo ${IMAGE2}