version: v2beta1
name: pipelines

vars:
  MELLO: $(echo ${DELLO})
  DELLO: ${MELLO}-${CHELLO}
  HELLO: ${devspace.namespace}-${DELLO}

pipelines:
  dev:
    steps:
      - run: |-
          echo "Hello World!"
