version: v2beta1
name: pipelines

dependencies:
  dep2:
    source:
      path: dep2.yaml

commands:
  test2:
    command: |
      build_images tes
  test:
    command: |
      run_command test2 abc

pipelines:
  helper:
    steps:
      - run: |-
          sleep 10
  dev:
    steps:
      - run: |-
          SWAG=fabi run_command test abc
          #run_dependency_pipelines --all --pipeline dev
          
          #export TEST=$(run_pipelines helper)
          #echo $TEST > swag.txt
          
          #build_images test --set image=${IMAGE}
          
          #create_deployments test2
          
          # Start development mode for test here
          #start_dev test --set imageSelector=${runtime.images.test} \
          #               --set terminal.command=sh