version: v2beta1
name: pipelines
pipelines:
  dev:
    steps:
      - run: |-
          kubectl apply -f my-manifest.yaml
          
          start_dev --set imageSelector=nginx \
                    --set terminal.enabled=true
  purge:
    steps:
      - run: |-
          stop_dev --all
          kubectl delete -f my-manifest.yaml