version: v2beta1
name: pipelines

vars:
  HELLO: test
  DEVSPACE_LOG_TIMESTAMPS: true

pipelines:
  dev:
    steps:
      - run: |-
          create_deployments test --set helm.values.containers[0].image=ubuntu
          echo "${HELLO} ${DEVSPACE_NAMESPACE}"
