version: v2beta1
name: pipelines

imports:
  - git: github.com/my-devspace/devspace



images:
  test-1: ...
  test-10: ...

dev:
  test: # -> select 1 pod
    imageSelector: nginx
    sync:
      - ...
      - ...
    terminal: ...
  test-2: # -> select 1 pod
    ...

pipelines:
  deploy:
    steps:
      - run: |-
          create_deployments test --set helm.componentChart=true \
                                  --set helm.values.containers[0].image=nginx
  dev:
    steps:
      - run: |-
          run_pipelines deploy --background

          start_dev test --set imageSelector=nginx \
                         --set terminal.command=bash \
                         --set sync[0].containerPath=/app \
                         --set sync[0].onUpload.restartContainer=true