version: v2beta1
name: pipelines

pipelines:
  dev:
    steps:
      - run: |-
          create_deployments test --set helm.componentChart=true \
                                  --set helm.values.containers[0].image=nginx

          start_dev test --set imageSelector=nginx \
                         --set logs.disabled=false \
                         --set command[0]=sh \
                         --set command[1]=-c \
                         --set 'command[2]=while true; do sleep 2 && echo Hello; done' \
                         --set sync[0].containerPath=/app \
                         --set sync[0].onUpload.restartContainer=true
