version: v2beta1
name: pipelines

deployments:
  - name: quickstart
    helm:
      componentChart: true
      values:
        containers:
          - image: ${runtime.images.test}

dev:
  quickstart:
    imageSelector: ${runtime.images.test}
    terminal: {}

pipelines:
  dev:
    steps:
      - run: |-
          build test --set image=testme \
            --set build.docker.skipPush=true
          
          deploy --all
          start_dev --all
