version: v2beta1
name: pipelines

vars:
  - name: IMAGE
    value: testme

pipelines:
  dev:
    steps:
      - run: |-
          build test --set image=${IMAGE} --set build.docker.skipPush=true
          
          deploy test --set helm.componentChart=true \
            --set helm.values.containers[0].image=${IMAGE}
          
          dev test --set imageSelector=${IMAGE} \
            --set terminal.command=sh
