name: Check Docs

on:
  pull_request:

jobs:

  check-docs:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          # Checkout as many commits as needed for the diff
          fetch-depth: 2

      # Fetch from compatibility table all the distros supported
      - id: check_file_changed
        run: |
          ./gendocs.sh
          if git diff --name-only | grep -E "^docs|devspace-schema.json"; then
            echo "{CHANGED}={TRUE}" >> $GITHUB_OUTPUT
          else
            echo "{CHANGED}={FALSE}" >> $GITHUB_OUTPUT
          fi

      - uses: mshick/add-pr-comment@v2
        with:
          if: needs.check_file_changed.outputs.changed == "True"
          allow-repeats: true
          message: |
            **Docs Update Needed!**
            It seems like you need to run `gendocs.sh` in order to update the docs.
            Please run this command and commit before merging.
            Thanks!
